version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
    environment:
      APP_ENV: spec
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn ci

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
